<a href="https://colab.research.google.com/github/jaejun22/dl05/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ch02_numpy.ipynb
- numpy 공부

In [1]:
# chap02 - numpy
import numpy as np


In [5]:

# ndarray
a = np.array([1, 2, 3])

print(a[0])
a, type(a)


1


(array([1, 2, 3]), numpy.ndarray)

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b)

b[0][2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [8]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

a.shape,a.ndim,a.dtype,a.itemsize,a.size


((3, 3), 2, dtype('int64'), 8, 9)

In [9]:
np.zeros( (3, 4) )	


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:

np.ones( (3, 4), dtype=np.int32 )


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [11]:

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:

x = np.ones(5, dtype=np.int64)

x


In [12]:

print(np.arange(5))

print(np.arange(1, 6))

np.arange(1, 10, 2)


[0 1 2 3 4]
[1 2 3 4 5]


array([1, 3, 5, 7, 9])

In [13]:

np.linspace(0, 10, 100)


array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:

# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:

# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])
x,y

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [21]:
#np.concatenate((x, y), axis=0)
# np.concatenate((x, y), axis=1)
#np.vstack((x, y))
np.hstack((x, y))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [22]:

# reshape
a = np.arange(12)

a.shape


(12,)

In [26]:

#a.reshape(3, 4)

#a.reshape(6, -1)
a.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:

array = np.arange(30).reshape(-1, 10)

array, array.shape


(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [29]:

arr1, arr2 = np.split(array, [3], axis=1)

arr1,arr2


(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]), array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29]]))

In [30]:

# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape


(6,)

In [31]:

a1 = a[np.newaxis, :]

a1,a1.shape


(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [32]:

a2 = a[:, np.newaxis]

a2.shape


(6, 1)

###numpy - indexing & slicing

In [34]:

# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

ages[1:3] ,ages[:2] 


(array([19, 25]), array([18, 19]))

In [ ]:

y = ages > 20

print(y)
# 조건을 만족하는 데이터 선택
ages[ ages > 20 ]


In [35]:

# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

a


3


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [36]:

# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]


array([[2, 3],
       [5, 6]])

### numpy 연산
- elementery 


In [ ]:

# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result


### 브로드캐스킹(broadcasting)

In [37]:

miles = np.array([1, 2, 3])

result = miles * 1.6

result


array([1.6, 3.2, 4.8])

In [38]:
# elementwise multiplication
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [39]:
# vectorwise multiplication
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result


array([[12, 12],
       [30, 30],
       [48, 48]])

In [40]:
arr1.dot(arr2)

array([[12, 12],
       [30, 30],
       [48, 48]])

In [41]:

A = np.array([0, 1, 2, 3])

10 * np.sin(A)


array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [42]:

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(),a.min(),a.max()


(45, 1, 9)

In [43]:
a.argmin(),a.argmax()

(0, 8)

In [44]:

scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    
scores.mean()
scores.mean(axis=0)
scores.mean(axis=1)

83.75

## 무작위수 배열

In [45]:

# random numbers
np.random.seed(100)

#np.random.rand(5),np.random.rand(5)

#np.random.rand(5, 3)

#np.random.randn(5)

#np.random.randn(5, 4)


(array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886]),
 array([0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333]))

###[DIY]
- 컬러 이미지 100장을 무작위로 생성
- 이미지 크기는 28x28

In [46]:
image100 = np.random.randn(100,28,28,3)
image100.shape

(100, 28, 28, 3)

In [48]:

m, sigma = 10, 2

m + sigma*np.random.randn(5)


array([10.2881178 , 16.42429223,  8.80377882,  6.92732875, 11.28182048])

In [49]:

mu, sigma = 0, 0.1 	# 평균과 표준 편차

np.random.normal(mu, sigma, 5)


array([-0.00698337,  0.20628942, -0.09369964,  0.00361993, -0.06802755])

###np.unique()

In [53]:

# unique()
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
#a.size
unique_values = np.unique(a)
unique_values


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
uv, ui = np.unique(a, return_index=True)
uv,ui

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [58]:
uv, uc = np.unique(a, return_counts=True)
uv,uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [ ]:

# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


x.flatten()


## pandas. , matplotlib

In [ ]:

########################
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 





